name: Build and Deploy to Prod ECS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.SIAL_BHAI_ACC_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SIAL_BHAI_ACC_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.SIAL_BHAI_ACC_AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Image to ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: sdk-cdk-git-first-ecr
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # 1. Image Build karein (SHA Tag ke sath)
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          
          # 2. Usi image par "latest" ka sticker (Tag) lagayen [NEW STEP]
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest

          # 3. Dono Tags ko Push karein [NEW STEP]
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          
          # Deployment ke liye hum specific SHA tag hi use karenge (Best Practice)
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # --- Task Definition Download Step ---
      - name: Download Task Definition
        run: |
          TASK_DEF_ARN=$(aws ecs describe-services --cluster sdk-cdk-git-first-cluster --services sdk-cdk-git-first-cluster --query "services[0].taskDefinition" --output text)
          aws ecs describe-task-definition --task-definition $TASK_DEF_ARN --query taskDefinition > task-definition.json

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.json
          service: sdk-cdk-git-first-cluster
          cluster: sdk-cdk-git-first-cluster
          image: ${{ steps.build-image.outputs.image }}
          wait-for-service-stability: true